name: Foundation Patterns Configuration Marketing
type: module
description: Pre-packaged Marketing Site building block kit configuration to jump start the use of the Foundation Patterns theme.
# core: 8.x
package: User interface
dependencies:
  - foundation_patterns_config
# Information added by Drupal.org packaging script on 2017-09-15
version: '8.x-1.0-alpha1'
core: '8.x'
project: 'foundation_patterns_config'
datestamp: 1505498649
